version: "2"
services:
  postgres:
    image: postgres:9.6.5
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_DB=${dbname}
      - POSTGRES_USER=${dbuser}
      - POSTGRES_PASSWORD=${dbpassword}
    restart: 'no'
  volumes:
    - postgres-vol:/var/lib/postgresql/data
volumes:
  postgres-vol:
    driver: local