# postgres ------------------------------------------
postgres-data:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
  container_name: postgres-datastore

postgresql:
  image: postgres
  environment:
    POSTGRES_USER: hoge
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
  container_name: postgres-db
  volumes_from:
      - postgres-data
# ---------------------------------------------------