mysql:
  image: ${MYSQL_IMAGE}
  restart: always
  environment:
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  volumes:
    - /var/lib/mysql
  ports:
    - ${MYSQL_PORT}:3306
