.catalog:
  name: "mysql"
  version: v0.0.1
  description: "MySQL"
  uuid: mysql-0
  questions:
    - variable: "MYSQL_IMAGE"
      description: "The docker image to use for the MySQL server."
      label: "MySQL Docker Image"
      type: "enum"
      options:
        - "mysql:latest"
        - "mysql:8.0.1"
        - "mysql:8.0"
        - "mysql:8"
        - "mysql:5.7.18"
        - "mysql:5.7"
        - "mysql:5"
        - "mysql:5.6.36"
        - "mysql:5.6"
        - "mysql:5.5.56"
        - "mysql:5.5"
        - "mariadb:latest"
        - "mariadb:10.3.0"
        - "mariadb:10.3"
        - "mariadb:10.2.6"
        - "mariadb:10.2"
        - "mariadb:10.1.24"
        - "mariadb:10.1"
        - "mariadb:10"
        - "mariadb:10.0.31"
        - "mariadb:10.0"
        - "mariadb:5.5.56"
        - "mariadb:5.5"
        - "mariadb:5"
      default: "mysql:latest"
      required: true
    - variable: "MYSQL_ROOT_PASSWORD"
      description: "The password that will be set for the MySQL root superuser account."
      label: "MySQL Root Password"
      required: true
      type: "password"
      default: "HghiiDGKJ5eo309dDAS4dad29394"
    - variable: "MYSQL_DATABASE"
      description: "Optional, allows you to specify the name of a database to be created on image startup."
      label: "MySQL Database Name"
      required: false
      type: "string"
    - variable: "MYSQL_USER"
      description: "Creates an additional MySQL (super)user. MySQL Password must also be set."
      type: "string"
      label: "Mysql User"
      default: "mysql"
    - variable: "MYSQL_PASSWORD"
      description: "A password for the additional MySQL (super)user. MySQL User must also be set."
      type: "password"
      label: "Mysql Password"
      default: "udysfJEORAGJAOIERJGOFLJs34534323"
    - variable: "MYSQL_PORT"
      type: "integer"
      label: "MySQL Server Port"
      description: "Public port for access to MySQL Server"
      default: "3306"
