postgres:
  image: postgres:10.1
  restart: always
  environment:
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  volumes:
    - postgres-vol:/var/lib/postgresql/data
  ports:
    - ${POSTGRES_PORT}:5432
