.catalog:
  name: Postgres
  version: latest
  uuid: postgres-1
  questions:
  - variable: POSTGRES_PORT
    description: 'Postgres exposed port'
    label: 'Port:'
    required: true
    default: 5432
    type: int
  - variable: POSTGRES_DATABASE
    description: 'Postgres database'
    label: 'Database:'
    required: true
    default: sample
    type: string
  - variable: POSTGRES_USER
    description: 'Postgres user'
    label: 'User:'
    required: true
    default: sample
    type: string
  - variable: POSTGRES_PASSWORD
    description: 'Postgres password'
    label: 'Password:'
    required: true
    default: asdf1234
    type: string
