version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    tty: true
    stdin_open: true
    ports:
      - ${postgres_port}:5532/tcp
    volumes_from:
      - postgres-data

    volumes:
      - postgresdb-vol:/var/lib/postgresql/data

volumes:
  postgresdb-vol:
    driver: local
